# Site settings
title: Erik Sylvester Hellenbrand
email: 
permalink: /blog/:year/:month/:day/:title/
description: > # this means to ignore newlines until "baseurl:"
  Personal site for Erik Hellenbrand
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erikhellenbrand.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  slvstr
linkedin_url: www.linkedin.com/in/erikhellenbrand

# Build settings
markdown: kramdown
